// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Vortex.Sspi
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "vortex_sspi";





        /// <summary>
        ///  # Safety
        ///  Caller must ensure that `input_ptr` is valid for `input_len` bytes and points to properly initialized memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "process_token", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SspiResult process_token(byte* input_ptr, uint input_len);

        /// <summary>
        ///  # Safety
        ///  Caller must ensure that `ptr` and `len` match a previously allocated buffer from this library.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_buffer(byte* ptr, uint len);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SspiResult
    {
        public int status;
        public byte* out_ptr;
        public uint out_len;
    }



}
